name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: npm run build
      - name: Check output directory
        run: |
          ls -la
          echo "Current directory contents:"
          find . -type d -maxdepth 2
      - name: Ensure out directory exists with correct content
        run: |
          if [ -d "out" ]; then
            echo "Out directory exists"
          else
            echo "Creating out directory"
            mkdir -p out
          fi
          
          if [ ! -f "out/index.html" ] && [ -f ".next/server/pages/index.html" ]; then
            echo "Copying index.html from .next/server/pages/"
            cp .next/server/pages/index.html out/
          fi
          
          if [ ! -f "out/index.html" ]; then
            echo "Creating basic index.html that redirects to /camilo-castillo/"
            echo '<!DOCTYPE html>' > out/index.html
            echo '<html>' >> out/index.html
            echo '<head>' >> out/index.html
            echo '  <meta charset="utf-8">' >> out/index.html
            echo '  <title>Redirecting...</title>' >> out/index.html
            echo '  <meta http-equiv="refresh" content="0; URL=/camilo-castillo/">' >> out/index.html
            echo '  <link rel="canonical" href="/camilo-castillo/">' >> out/index.html
            echo '</head>' >> out/index.html
            echo '<body>' >> out/index.html
            echo '  <p>Redirecting to <a href="/camilo-castillo/">/camilo-castillo/</a>...</p>' >> out/index.html
            echo '</body>' >> out/index.html
            echo '</html>' >> out/index.html
          fi
          
          if [ -d ".next/static" ]; then
            echo "Copying static files"
            mkdir -p out/_next
            cp -r .next/static out/_next/
          fi
          
          if [ -d "public" ]; then
            echo "Copying public files"
            cp -r public/* out/
          fi
          
          echo "Out directory contents:"
          ls -la out || echo "Out directory is empty"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 
        